# Generated by Django 4.1 on 2022-08-30 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="courseid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courseAttendance",
                to="api.course",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="studentid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studentAttendance",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="enrolled",
            name="courseid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courseEnrolled",
                to="api.course",
            ),
        ),
        migrations.AlterField(
            model_name="enrolled",
            name="studentid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studentEnrolled",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="instructors",
            name="courseid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courseInstructor",
                to="api.course",
            ),
        ),
        migrations.AlterField(
            model_name="instructors",
            name="teacherid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacherInstructor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
