# Generated by Django 4.1 on 2022-08-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="isabsent",
            field=models.BooleanField(default=True),
        ),
    ]
