# Generated by Django 4.1 on 2022-08-30 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_attendance_date_alter_attendance_isabsent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(),
        ),
    ]
